# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish Package

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:

  build:
    name: Build Package
    uses: ./.github/workflows/build.yml

  publish:  
    name: Pack and Publish
    runs-on: ubuntu-latest
    needs: build
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: 9.0.x
      
      - name: Pack
        run: dotnet pack -c Release src/ResultT/ResultT.csproj -o publish
        
      - name: Publish
        run: dotnet nuget push publish/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
        